"""create_risk_engine_tables

Revision ID: ee6a8a9231ea
Revises: f571b74b2eaa
Create Date: 2026-07-17 21:04:52.023737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee6a8a9231ea'
down_revision: Union[str, Sequence[str], None] = 'f571b74b2eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('factor_type', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trips'
    )
    op.create_index(op.f('ix_trips_risk_events_is_active'), 'risk_events', ['is_active'], unique=False, schema='trips')
    op.create_index(op.f('ix_trips_risk_events_trip_id'), 'risk_events', ['trip_id'], unique=False, schema='trips')
    
    op.create_table('trip_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trips'
    )
    op.create_index(op.f('ix_trips_trip_risks_trip_id'), 'trip_risks', ['trip_id'], unique=True, schema='trips')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_trip_risks_trip_id'), table_name='trip_risks', schema='trips')
    op.drop_table('trip_risks', schema='trips')
    
    op.drop_index(op.f('ix_trips_risk_events_trip_id'), table_name='risk_events', schema='trips')
    op.drop_index(op.f('ix_trips_risk_events_is_active'), table_name='risk_events', schema='trips')
    op.drop_table('risk_events', schema='trips')
    # ### end Alembic commands ###
